language: node_js
node_js:
- 6.10.2
before_deploy:
  - pip install --user awscli
  - mkdir -p dist/builds/$TRAVIS_COMMIT/$TRAVIS_BUILD_ID
  - npm run dist
  - |
    aws cloudformation package \
      --template-file particles/cftemplates/lf-lex.template.yml \
      --s3-bucket lambda-formation.$AWS_REGION \
      --s3-prefix lf-lex/builds/$TRAVIS_COMMIT/$TRAVIS_BUILD_ID \
      --output-template-file dist/builds/$TRAVIS_COMMIT/$TRAVIS_BUILD_ID/lf-lex.template.yml
  - mv dist/lambda.zip dist/lf-lex.zip
  #- mkdir -p ./dist/builds
  #- mkdir -p ./dist/releases
  #- mv ./dist/lambda.zip ./dist/builds/lf-lex-$TRAVIS_COMMIT-$TRAVIS_BUILD_ID-$TRAVIS_NODE_VERSION.zip
  - |
    if [ -z "$TRAVIS_TAG" ]; \
      then \
        mkdir -p dist/releases/$TRAVIS_TAG/latest \
        && cp dist/builds/$TRAVIS_COMMIT/$TRAVIS_BUILD_ID/lf-lex.template.yml \
          dist/releases/$TRAVIS_TAG/latest/lf-lex.template.yml; \
    fi
  - |
    if [ -z "$TRAVIS_BRANCH" ]; \
      then \
        mkdir -p dist/branches/$TRAVIS_BRANCH/latest \
        && cp dist/builds/$TRAVIS_COMMIT/$TRAVIS_BUILD_ID/lf-lex.template.yml \
          dist/branches/$TRAVIS_BRANCH/latest/lf-lex.template.yml; \
    fi
env:
  - AWS_REGION=us-east-1
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: lambda-formation.$AWS_REGION
  region: $AWS_REGION
  upload-dir: lf-lex
  skip_cleanup: true
  local_dir: dist

