language: node_js
node_js:
- 6.10.2
- 4.3.2
before_deploy:
  - mkdir dist
  - npm run dist
  - mkdir -p ./dist/builds
  - mkdir -p ./dist/releases
  - mv ./dist/lambda.zip ./dist/builds/lf-lex-$TRAVIS_COMMIT-$TRAVIS_BUILD_ID-$TRAVIS_NODE_VERSION.zip
  - if [ -n $TRAVIS_TAG ]; then mv ./dist/lambda.zip ./dist/builds/lf-lex-$TRAVIS_TAG-$TRAVIS_NODE_VERSION.zip; fi
  - if [ -n $TRAVIS_BRANCH ]; then mv ./dist/lambda.zip ./dist/builds/lf-lex-$TRAVIS_BRANCH-$TRAVIS_NODE_VERSION.zip; fi
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: lambda-formation.us-east-1
  region: us-east-1
  upload-dir: lf-lex
  skip_cleanup: true
  local_dir: dist

